### PR TITLE
process variable only if it's contains in template

### PR DESCRIPTION
**Pull request by bioker**
For example, if i will use function 'input' with variables i think it will be not necessary input it each time even if this variable not needed for template

### CODE REVIEW

**Comment by KabbAmine** [comment]
Thanks for your contribution, but I cannot understand the logic of your PR.

Please check my comments.

**Comment by bioker** [comment]
It's chunk of my vimrc file: 
```
let g:vbox.variables = {
    \ '%CLASS%' : 'f=TemplateInputClassVar()',
    \ '%METHOD%' : 'f=TemplateInputMethodVar()',
    \ '%CYCLE_VAR%' : 'f=TemplateInputCycleVarVar()',
    \ '%CYCLE_CONDITION%' : 'f=TemplateInputCycleCondVar()',
    \ '%IF_CONDITION%' : 'f=TemplateInputIfCondVar()',
    \ '%PACKAGE%' : 'f=TemplateInputPackageVar()'
    \ }
function! TemplateInputClassVar()
    return input('Enter class name:')
endfunction
...
```

If i will use this, i will enter all of my input functions, even if this variable not present on template, so, maybe will be better if it will process only if variable is present? 
This is what i implement in my PR, i just add checking for variable presence in template before this variable will be processed.

**Comment by KabbAmine** [comment]
I see.

You are using vBox the wrong way. The plugin is a **template** manager not a snippet manager, your implementation is quite interesting with the `input`'s but it will be a pain in the ass to manage snippets this way.

My advice is to use an appropriate plugin for snippets (I recommend Ultisnippets or snipmate if you want a full viml plugin), and use vBox only for file templates, так будет лучше.

**Comment by bioker** [comment]
Ok, i understood) Thank you for your advice, I will definitely try these plugins)

**Pull request closed without merging**
